# This is a basic workflow to help you get started with Actions
 
name: CICD Workflow 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "feature/initial_development" branch
  push:
    branches: [ "Dev","QA","release","main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build with Maven 
        run: |
          echo "Success"
